// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package injection

import (
	"github.com/daffashafwan/deteksip/handler"
	"github.com/daffashafwan/deteksip/repository"
	"github.com/daffashafwan/deteksip/service"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitMahasiswaAPI(db *gorm.DB) handler.UserAPI {
	userRepository := repository.ProviderUserRepository(db)
	userService := service.ProviderUserService(userRepository)
	userAPI := handler.ProviderUserAPI(userService)
	return userAPI
}

func InitTipeSoalAPI(db *gorm.DB) handler.TipeSoalAPI {
	tipeSoalRepository := repository.ProviderTipeSoalRepository(db)
	tipeSoalService := service.ProviderTipeSoalService(tipeSoalRepository)
	tipeSoalAPI := handler.ProviderTipeSoalAPI(tipeSoalService)
	return tipeSoalAPI
}

func InitAuthAPI(db *gorm.DB) handler.AuthAPI {
	userRepository := repository.ProviderUserRepository(db)
	authService := service.ProviderAuthService(userRepository)
	authAPI := handler.ProviderAuthAPI(authService)
	return authAPI
}

func InitSoalAPI(db *gorm.DB) handler.SoalAPI {
	soalRepository := repository.ProviderSoalRepository(db)
	soalService := service.ProviderSoalService(soalRepository)
	soalAPI := handler.ProviderSoalAPI(soalService)
	return soalAPI
}
