// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injection

import (
	"github.com/daffashafwan/deteksip/handler"
	"github.com/daffashafwan/deteksip/repository"
	"github.com/daffashafwan/deteksip/service"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitMahasiswaAPI(db *gorm.DB) handler.UserAPI {
	UserRepository := repository.ProviderUserRepository(db)
	mahasiswaService := service.ProviderUserService(UserRepository)
	mahasiswaAPI := handler.ProviderUserAPI(mahasiswaService)
	return mahasiswaAPI
}
