name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    ## checks out our project source code
    - uses: actions/checkout@v2
    
    ## Builds our docker image!
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag daffashafwan/deteksip:$(date +%s)

    ## Publishes our image to Docker Hub 😎
    - name: Publish to Registry
      uses: daffashafwan/deteksip@main
      with:
        ## the name of our image
        name: daffashafwan/deteksip
        ## Here we pass in our Docker Username
        username: ${{ secrets.DOCKER_USERNAME }}
        ## and our Docker password which 
        password: ${{ secrets.DOCKER_PASSWORD }}
